[0909] 스텍, 큐, 덱 과제
Altu-Bitu-3/Altu-Bitu-HaeSeungJeon pull request #3
Opened 2022-09-14 18:55 UTC by JeonHaeseung

#### 내용 & 질문
> 스텍, 큐, 덱 과제 4개 제출합니다!

#### <기존 제출>
> 문제 번호 1918, 4889, 11866, 17299

2022-09-15 11:36 UTC, flowersayo reviewed
안녕하세요 혜승님!!!!
1918번이 꽤 난이도 있는 문제였음에도 불구하고 너무 훌륭하게 잘 풀이해주셨어요🥺
오늘 밤 즈음에 1918번 관련한 문제 풀이 해결과정을 다룬 PDF 자료가 올라갈텐데
복습차원에서 한번 더 확인해보셔도 좋을 것 같아요! 😊
p1 커멘트는 꼭 수정해주셨으면 하는 부분이고, p2,p3는 참고만해주셔도 괜찮습니다!
수정하시고싶은 부분 있으시면 고치시고 저 리뷰어로 호출해주세요~!
수고하셨습니다🤗💛

2022-09-15 11:36 UTC, flowersayo commented on [0909] 스텍, 큐, 덱 과제/0909 백준 1918.cpp
> +}
저희가 제공드리는 샘플코드랑 똑같아서 더 첨언드릴게 없네요 🥺🥺
완벽합니다👍

2022-09-15 16:37 UTC, jk0527 requested changes
P1. 11866 코드리뷰 완료

혜승님 안녕하세요!
주석이 정말 친절하고 깔끔해서 코드 리뷰에 정말 많이 도움이 되었습니다!! 모듈러 연산을 이용한 방법도 정말 좋지만 코딩 테스트를 할 때는 빠르게 문제를 풀어야 해서 규칙을 떠올리기 조금 어려울 수도 있을 것 같아요..! 스텍, 큐, 덱 과제인만큼 자료구조를 이용해서 풀어보시는 것은 어떨까요?? 수정하시고(아니면 새로운 버전을 추가하셔도 돼요!) 리뷰어 호출해주세요!😊😊

2022-09-15 16:37 UTC, jk0527 commented on [0909] 스텍, 큐, 덱 과제/0909 백준 11866.cpp
> +    //규칙: 다음으로 지울 원소의 인덱스 = (저번에 지운 원소 인덱스+(k-1))%(남은 원소 갯수)
와 주석 정말 꼼꼼하게 달아주셨네요!! 이해에 도움이 많이 되었습니다!!😎😎 (코드 중간이 아니라 맨 앞에 있어도 좋을 것 같아요!)

2022-09-15 16:37 UTC, jk0527 commented on [0909] 스텍, 큐, 덱 과제/0909 백준 11866.cpp
> +    ios::sync_with_stdio(0); cin.tie(0); cout.tie(0);
(그냥 참고로) 이 문제는 이 부분이 없어도 시간 초과가 나지는 않습니다!

2022-09-15 16:37 UTC, jk0527 commented on [0909] 스텍, 큐, 덱 과제/0909 백준 11866.cpp
> +        start = (start + (k-1))%n; //삭제할 원소 인덱스 구하기
모듈러 연산을 사용해서 푸셨네요!!😎 모듈러 연산을 사용하려면 위에 주석 달아주신 것처럼 계산을 하고 식을 만드는 과정이 필요할 것 같아요! 하지만 이 문제는 스텍, 큐, 덱 중 하나를 사용하면 조금 더 쉽게 풀 수 있어요! 어떤 자료구조를 사용하면 될까요?

2022-09-15 20:12 UTC, jaeseo222 reviewed
**p2. 17299 코드 리뷰 완료**

안녕하세요 혜승님🤗
쉽지 않은 문제였는데, 너무 잘 풀어주시고 주석도 작성해주셔서 너무 좋았습니다. 🔥

가독성에 관한 피드백 및 코멘트 달았으니, 확인 부탁 드립니다 !
**수정하신 부분 있으시면 리뷰어로 불러주셔도 좋습니다!**
수고 많으셨습니다. 감사합니다.😄😄

2022-09-15 20:12 UTC, jaeseo222 commented on [0909] 스텍, 큐, 덱 과제/0909 백준 17299.cpp
> +int F[1000001], ans[1000001], num[1000001]; //인덱스가 숫자 a가 되고, 요소가 F(a) 즉 우선순위가 되는 배열 F
p3. 1000001은 여러 번 쓰이고 수열 A의 최대 크기라는 의미 있는 수니까 상수로 선언 해줘도 좋겠네요!
특히, `1000000`은 `1e6` 으로도 표기 가능합니다!

예를 들어, **1e9은 "1에 10의 9제곱을 곱한"** 의미입니다.
그러니까 **1e(10의 지수)** 가 **1 x 10 (10의 지수)** 라고 생각해주시면 편하게 표기 가능합니다 😉😉
더 자세한 내용은 10의 배수가 많이 사용되는 **지수 표기법**을 참고해주시면 될 것 같습니다.

2022-09-15 20:12 UTC, jaeseo222 commented on [0909] 스텍, 큐, 덱 과제/0909 백준 17299.cpp
> +int F[1000001], ans[1000001], num[1000001]; //인덱스가 숫자 a가 되고, 요소가 F(a) 즉 우선순위가 되는 배열 F
p3. `F`라는 변수명은 가독성 면으로 봤을 때, 등장한 횟수라는 의미가 잘 전달되지 않는 것 같아요! 
직관적으로 와 닿을 수 있도록 `cnt` 혹은 `frequency` 는 어떨까요?

2022-09-15 20:12 UTC, jaeseo222 commented on [0909] 스텍, 큐, 덱 과제/0909 백준 17299.cpp
> +int F[1000001], ans[1000001], num[1000001]; //인덱스가 숫자 a가 되고, 요소가 F(a) 즉 우선순위가 되는 배열 F
p2. **불필요한 전역변수는 지양**하는 것이 좋습니다!! 😄

현재는 코드가 길지 않아 큰 문제가 없지만! 함수 내에서만 사용하는 변수를 전역변수로 선언할 경우, 디버깅이 어려워서 버그를 고치기 어려울 수 있고, 코드가 길어지면 수정하기 어려운 문제가 생기기도 합니다.

물론, 특정 변수를 다양한 함수에서 접근해야 한다면 전역변수로 선언하여 유용하게 사용할 수 있습니다. 🙂

2022-09-15 20:12 UTC, jaeseo222 commented on [0909] 스텍, 큐, 덱 과제/0909 백준 17299.cpp
> +		st.push(i); //스텍이 empty 상태면 push
p2. 현재 **오등큰수가 될 수 있는 수의 인덱스**를 push해주고 있네요!! `num[st.top()]`함으로써 num에 참조하여 **오등큰수가 될 수 있는 숫자**에 접근하는 방법 너무 좋아요!!

그런데, 조금은 더 간단하게 생각해볼 수 있을 것 같습니다.
오등큰수가 될 수 있는 숫자를 알기 위해선 어차피 num에 참조하여 숫자에 접근해줘야 할 텐데, 그렇다면 꼭 인덱스를 push 할 수 밖에 없을까요??😉😉

2022-09-16 11:32 UTC, 0321minji commented
**4889 코드리뷰 완료**
안녕하세요 혜승님!😃

작성해주신 코드 잘 봤습니다!
주석도 꼼꼼하게 달아주셔서 리뷰 드리기 너무 좋았어요👍👍
샘플코드와 유사하게 풀어주셨는데 디테일한 부분만 살짝씩 다른 것 같아요~ 어떻게 구현했는지 참고해주시면 좋을 것 같습니다!
간단한 코멘트 남기니 확인 부탁드려요!
수고하셨습니다🙌🙌

2022-09-21 10:16 UTC, 0321minji commented on [0909] 스텍, 큐, 덱 과제/0909 백준 4889.cpp
> +                }
p3.
주석 다신것처럼 오른쪽 괄호가 나타난 경우에 스택에 있는 괄호가 왼쪽인지 아닌지 확인하므로 굳이 map을 사용하지 않고 직접 비교해주셔도 괜찮을 것 같네요!!

2022-09-21 10:16 UTC, 0321minji commented on [0909] 스텍, 큐, 덱 과제/0909 백준 4889.cpp
> +        cout << ++s_num << ". " << isStable(s) << '\n'; //문자열이 있으면 최소 연산의 수 출력
출력하면서 동시에 넘버 증가시켜준 것 좋아요~!!

2022-09-24 08:20 UTC, JeonHaeseung commented on [0909] 스텍, 큐, 덱 과제/0909 백준 17299.cpp
> +		st.push(i); //스텍이 empty 상태면 push
@jaeseo222 안녕하세요! 설명해주신 코드 리뷰 전부 반영하였으니 확인 부탁드립니다. 특히 num의 인덱스가 아니라 num 자체를 스택에 저장하는 부분이 코드를 간단하게 만드는 데 큰 도움이 된 것 같습니다. 감사합니다!

2022-10-03 14:38 UTC, JeonHaeseung commented on [0909] 스텍, 큐, 덱 과제/0909 백준 11866.cpp
> +        start = (start + (k-1))%n; //삭제할 원소 인덱스 구하기
@jk0527 안녕하세요! 말씀주신대로, 큐 자료구조를 활용하여 문제를 다시 풀어보았습니다. 새로 제출한 코드는 0909 백준 11866[코드리뷰] 파일에 있습니다. (이유는 모르겠는데, 이 문제를 풀면서 push와 pop을 통해 다시 큐에 넣어준다는 생각을 못하고 자꾸 중간에 삭제해야 한다고 생각했습니다😂) 확인 부탁드립니다. 감사합니다!

2022-10-03 14:43 UTC, JeonHaeseung commented on [0909] 스텍, 큐, 덱 과제/0909 백준 4889.cpp
> +                }
@0321minji 안녕하세요! 리뷰해 주신 부분 수정하여 업로드 하였습니다.(map를 삭제한 것만 빼고는 나머지는 같습니다!) 확인 부탁드립니다. 감사합니다:)

2022-10-04 06:43 UTC, jk0527 reviewed
P2. 11866 코드리뷰 완료

혜승님 안녕하세요!
제가 코멘트 드린 부분 잘 수정해주셨네요!!😎
큐를 잘 이용하신 것 같습니다!! 몇 가지 사소한 코멘트 남겼습니다!
수고하셨습니다!! 더 궁금한 점이 있으시면 리뷰어를 호출해주세요!!🥰🥰

2022-10-04 06:43 UTC, jk0527 commented on [0909] 스텍, 큐, 덱 과제/0909 백준 11866[코드리뷰].cpp
> +        for(int j=1;j<k;j++){
그냥 스타일이긴 한데 이중 루프를 피하고 싶으시면 while문과 cnt 변수를 사용하는 방법도 있습니다! (연산 횟수는 같습니다..!)

2022-10-04 06:43 UTC, jk0527 commented on [0909] 스텍, 큐, 덱 과제/0909 백준 11866[코드리뷰].cpp
> +        cout << q.front() << ", ";
입출력은 최대한 main함수에서 하는 것을 지향하고 있어서 vector에 순서대로 값을 저장하고 vector를 main으로 넘겨서 출력하는 방법도 있겠네요!

2022-10-04 06:43 UTC, jk0527 approved these changes

2022-10-04 07:04 UTC, JeonHaeseung commented on [0909] 스텍, 큐, 덱 과제/0909 백준 1918.cpp
> +}
@flowersayo 안녕하세요! 스텍과 큐 PR을 merge하고 싶은데, 아직 이모지를 안 남겨 주셔서 연락드립니다.

2022-10-05 11:42 UTC, merged